name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Verificar versión de PHP
      run: php -v

    - name: Diff composer.lock and .json
      run: git diff composer.lock

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    

    - name: Clear Composer Cache
      run: composer clear-cache


    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: update composer.lock
      run: composer update

    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
